
export default {
    zegoMartSearchHint : "Search items in ZegoMart",
    selectAll : "Select All",
    checkout : "CheckOut",
    shopCartEmpty: "There are no items in the cart",
    loadFailTip: "There was a problem loading, try refreshing",
    refresh: "Refresh",
    promotion: "Promotion：{0}",
    receiveSuccess:'receive success',
    differenceDiscount: "Difference {0} discount {1}",
    goodsSearchEmptyTip: "No items",
    goodsSearchEmptyAlert: "The data is incomplete",
    loading: "Loading...",
    noMoreDatas: "No more data",
    goodsDeleteAlert: "Confirm deleting the item?",
    shopCartMaxStorageError: "The maximum stock of this commodity has been reached",
    shopCartMaxLimitError: "The limit quantity of {0} pieces has been exceeded",
    noMoreCategoryGoods: "no more data",
    categoryNoGoods: "There are no products for the time being. Try to browse other categories",
}