
export default {
    zegoMartSearchHint: "搜索ZegoMart内商品",
    selectAll : "全选",
    checkout : "结算",
    shopCartEmpty: "购物车还没有商品哦",
    loadFailTip: "加载时遇到了问题，刷新一下试试",
    refresh: "刷新",
    promotion: "已优惠：{0}",
    receiveSuccess:'领取成功',
    differenceDiscount: "还差{0}减{1}",
    goodsSearchEmptyTip: "没有商品",
    goodsSearchEmptyAlert: "请输入搜索内容",
    loading: "加载中...",
    noMoreDatas: "没有更多数据",
    goodsDeleteAlert: "确认删除商品？",
    shopCartMaxStorageError: "已达到该商品最大库存",
    shopCartMaxLimitError: "已超过{0}件限购数量",
    noMoreCategoryGoods: "下面没有啦",
    categoryNoGoods: "暂时没有商品哦，试试看浏览其它分类",
}