# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
inhibit_all_warnings!

target 'GliKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for GliKit
  pod 'SDWebImage', '~> 5.15.8'
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 4.0.1', :subspecs => ["NSURLSession", "Reachability", "Security", "Serialization"]
  
  #数据库
  pod 'FMDB', '~> 2.7.5'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
