# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'GliKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GliKit
  pod 'SDWebImage', '~> 5.9.2'
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 4.0.1'
  
  #数据库
  pod 'FMDB', '~> 2.7.5'

end
