# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
target 'GliKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GliKitDemo
  pod 'GliKit', :path => '../GliKit'
  pod 'GliReacNativeKit', :path => '../GliReacNativeKit'
  pod 'IAPHelper'
end

target 'GliKitApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GliKitDemo
  pod 'GliKit', :path => '../GliKit'
end
